delivery/delivery/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('web/',include('web.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

delivery/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('producto/<int:producto_id>/', views.producto, name='producto'),
    path('categoria/<int:categoria_id>/', views.productoPorCategory, name='categoria'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('carrito',views.carrito,name='carrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name="eliminarProductoCarrito"),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito')
]

delivery/web/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to='categoria',blank=True,null=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField(default=0)
    imagen = models.ImageField(upload_to='productos',blank=True,null=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.nombre

delivery/web/views.py
from django.shortcuts import get_object_or_404, render

from .models import Producto
from .models import Categoria

# Create your views here.
def index (request):
    product_list = Producto.objects.order_by('nombre')[:11]
    category_list = Categoria.objects.all()
    context = {
        'product_list': product_list,
        'category_list' : category_list
        }
    return render(request, 'index.html', context)

def producto (request, producto_id):
    producto = Producto.objects.get(pk=producto_id)
    context = {
        'producto': producto
        }
    return render(request, 'producto.html',context)

def productoPorCategory (request, categoria_id):
    objCategoria = Categoria.objects.get(pk=categoria_id)
    product_list = Producto.objects.filter(categoria=objCategoria)
    category_list = Categoria.objects.all()
    context = {
        'product_list': product_list,
        'category_list' : category_list
        }
    return render(request, 'index.html', context)

def agregarCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.add(objProducto,1)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def eliminarProductoCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.remove(objProducto)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def limpiarCarrito(request):
    CarritoProducto = Cart(request)
    CarritoProducto.clear()
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def carrito(request):
    print(request.session.get("cart"))
    return render(request,'carrito.html')

delivery/web/templates/carrito.html
{% extends "layout.html" %}
{% block content %}
<div class="cart-area pd-top-120 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="table-responsive mb-4">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="blank"></th>
                                <th class="blank"></th>
                                <th class="blank"></th>
                                <th class="title-name">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th>Total Price</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for key,value in request.session.cart.items %}
                            <div class="media-body">
                                <a href="{% url 'tienda:producto' value.producto_id %}" class="d-block text-dark">{{ value.nombre }}</a>
                            </div>
                            <tr>
                                <td class="table-close-btn"><a href="#"><i class="ri-close-line"></i></a></td>
                                <th scope="row"><img src="{{ value.imagen }}" alt="img"></th>
                                <td colspan="2" class="item-name">
                                </td>
                                <td>{{ value.precio }}</td>
                                <td class="table-quantity">
                                    1
                                </td>
                                <td>{{ value.total }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>          
            </div>
        </div>
    </div>
</div>
<!-- cart area end -->    
{% endblock %}

delivery/web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<!-- category Area Start-->
<section class="category-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 align-self-center">
                <ul class="category-menu">
                    <li class="category-wrap">
                        {% for cat in category_list %}
                        <a href="{% url 'web:categoria' cat.id %}"><img src="{{ cat.imagen.url }}" alt="category">{{cat.nombre}}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- category Area End --> 

<!-- populer Area Start-->
<section class="populer-area pd-top-50 pd-bottom-120">
    {% for prod in product_list %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6">
                <div class="single-item-wrap">
                    <div class="thumb">
                        <img src="{{ prod.imagen.url }}" alt="img">
                        <a class="fav-btn" href="#"><i class="ri-heart-line"></i></a>
                    </div>
                    <div class="wrap-details">
                        <h5><a href="{% url 'web:producto' prod.id %}">{{ prod.nombre }}</a></h5>
                        <div class="wrap-footer">
                            <h6 class="price">S/ {{ prod.precio }}</h6>
                        </div>                            
                    </div>
                    <div class="btn-area">
                        <a class="btn btn-secondary" href="detalle.html">DETALLE </a>         
                    </div> 
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</section>
{% endblock %}

delivery/web/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>delivery</title>
    <!--fivicon icon-->
    <link rel="icon" href="{% static 'assets/img/fevicon.png' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick-slide.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700;800&family=Bebas+Neue&family=Satisfy&family=Quattrocento:wght@400;700&display=swap" rel="stylesheet">


</head>
<body class='sc5'>
    <!-- preloader area start -->
    <div class="preloader" id="preloader">
        <div class="preloader-inner">
            <div id="wave1">
            </div>
            <div class="spinner">
                <div class="dot1"></div>
                <div class="dot2"></div>
            </div>
        </div>
    </div>
    <!-- preloader area end -->
    <!-- search popup area start -->
    <div class="body-overlay" id="body-overlay"></div>
    <div class="td-search-popup" id="td-search-popup">
        <form action="index.html" class="search-form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search.....">
            </div>
            <button type="submit" class="submit-btn"><i class="fa fa-search"></i></button>
        </form>
    </div>
    <!-- //. search Popup -->

    <!-- navbar start -->
    <header class="navbar-area">
        <nav class="navbar navbar-expand-lg">
            <div class="container nav-container">
                <div class="responsive-mobile-menu">
                    <button class="menu toggle-btn d-block d-lg-none" data-target="#themefie_main_menu" 
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-left"></span>
                        <span class="icon-right"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="themefie_main_menu">
                    <ul class="navbar-nav menu-open">
                        <li class="current-menu-item menu-item-has-children">
                            <a href="home-1.html">HOME</a>
                            <ul class="sub-menu ps-0">
                                <li><a href="home-1.html">Home 01</a></li>
                                <li><a href="home-2.html">Home 02</a></li>
                                <li><a href="home-3.html">Home 03</a></li>
                            </ul>
                        </li>
                        <li class="current-menu-item menu-item-has-children">
                            <a href="#">PAGES</a>
                            <ul class="sub-menu ps-0">
                                <li><a href="about.html">About</a></li>
                                <li><a href="blog.html">Blog</a></li>
                                <li><a href="blog-details.html">Blog Details</a></li>
                                <li><a href="menu.html">Menu</a></li>
                                <li><a href="menu-list.html">Menu List</a></li>
                                <li><a href="shop.html">Shop</a></li>
                                <li><a href="single-product.html">Shop Details</a></li>
                                <li><a href="cart.html">Cart</a></li>
                                <li><a href="checkout.html">Checkout</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="about.html">ABOUT US</a>
                        </li>
                        <li>
                            <a href="contact.html">CONTACTS</a>
                        </li>
                    </ul>
                </div>
                <div class="logo">
                    <a class="main-logo" href="/"><img src="{% static 'assets/img/logo.png' %}" alt="img"></a>
                </div>
                <div class="nav-right-part nav-right-part-mobile">
                    <ul>
                        <li><a class="search" href="#"><i class="ri-search-line"></i></a>
                        </li>
                        <li class="phone-contact d-md-block d-none"><i class="ri-phone-fill float-start"></i>
                            +997 509 153 849
                        </li>
                        <li class="menu-cart"><a href="cart.html">CART <span>1</span></a></li>
                        <li>49.50 $</li>
                    </ul>
                </div>
                <div class="nav-right-part nav-right-part-desktop">                    
                    <ul>
                        <li><a class="search" href="#"><i class="ri-search-line"></i></a>
                        </li>
                        <li class="phone-contact"><i class="ri-phone-fill float-start"></i>
                            +997 509 153 849
                        </li>
                        <li class="menu-cart"><a href="cart.html">CART <span>1</span></a></li>
                        <li>49.50 $</li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- navbar end -->

    <!-- bredcrumb Area Start-->
    <section class="breadcrumb-area">
        <div class="banner-bg-img"></div>
        <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
        <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 align-self-center">
                    <div class="banner-inner text-center">
                        <h3>Choose you items
                        </h3>
                        <h1>OUR MENU</h1>
                        <nav aria-label="breadcrumb">
                            <ul class="breadcrumb">
                              <li class="breadcrumb-item"><a href="home.html">Home</a></li>
                              <li class="breadcrumb-item active" aria-current="page">Menu Tab</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- bredcrumb Area End --> 
    {% block content %}
    {% endblock %} 

    <!-- footer area start -->
    <footer class="footer-area pd-top-100">
        
        <div class="footer-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-6 text-md-start text-center">
                        <div class="copyright-area">
                            <p>© 2021 Foodka. All Rights Reserved by Themefie</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer area end -->    

    <!-- back-to-top end -->
    <div class="back-to-top">
        <span class="back-top"><i class="fas fa-angle-double-up"></i></span>
    </div>

    

    <!-- all plugins here -->
    <script src="{% static 'assets/js/jquery.3.6.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/imageloded.min.js' %}"></script>
    <script src="{% static 'assets/js/counterup.js' %}"></script>
    <script src="{% static 'assets/js/waypoint.js' %}"></script>
    <script src="{% static 'assets/js/magnific.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.min.js' %}"></script>
    <script src="{% static 'assets/js/slick-slider.min.j' %}s"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/tweenmax.min.js' %}"></script>
    <!-- main js  -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

delivery/web/templates/producto.html
{% extends "layout.html" %}
{% block content %}
<!-- shop-details Area Start-->
<div class="shop-details-area pd-top-100">
    <div class="container">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                <div class="center">
                    <div class="col-md-6">
                        <img class="card-img-top mb-5 mb-md-0" src="{{ producto.imagen.url }}" alt="item">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="shop-item-details">                    
                    <h2 class="entry-title">{{ producto.nombre }}</h2>
                    <div class="row">
                        <div class="col-lg-6 align-self-center">
                            <h4 class="price">S/. {{ producto.precio }}</h4>
                        </div>                            
                    </div>   
                    <p class="mt-4">Contenido del Producto</p>
                    <a href="{% url 'web:agregarCarrito' producto.id %}" class="btn btn-secondary" role="button">AGREGAR AL CARRITO</a>
                </div>    
            </div>
        </div>
    </div>
</div>
{% endblock %}